login/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
]

login/prac_pro_2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'special/', views.special, name="special"),
    url(r'^logout/', views.user_logout, name="logout")
]

login/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    portfolia = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic')

    def __str__(self):
        return "Username: {}".format(self.user.username)

login/basic_app/forms.py
from django import forms
from basic_app.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    portfolia = forms.URLField(required=False)
    profile_pic = forms.ImageField(required=False)
    class Meta():
        model = UserProfileInfo
        fields = ('portfolia', 'profile_pic')

login/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

def index(request):
    msg_dir = {
        'title':'Welcome to the home page!'
    }
    return render(request, 'basic_app/index.html', context=msg_dir)

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print("UserForm errors: {}\nProfileForm errors: {}".format(user_form.errors, profile_form.errors))
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'basic_app/registration.html', {'registered':registered,'user_form':user_form, 'profile_form':profile_form})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        print("Username: {}, password: {}".format(username, password))
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active!")
        else:
            print("Someone try to login")
            print("Username: {}, password: {}".format(username, password))
            return HttpResponse("INVALID LOGIN DETAILS!")
    else:
        return render(request, 'basic_app/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("Login successfully")

login/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <a class="nav-brand" href="{% url 'index' %}">Home</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'admin:index'%}">ADMIN</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'basic_app:register' %}">REGISTER</a>
            </li>
            {% if user.is_authenticated %}
              <li class='nav-item'>
                <a class="nav-link text-light" href="{% url 'logout' %}">LOGOUT</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'basic_app:login' %}">LOGIN</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    {% block body_block %}
      <h1>This is base.html page</h1>
    {% endblock %}
  </body>
</html>

login/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1 style="backgroun-color: blue;">{{ title }}</h1>
    </div>
  </div>
{% endblock %}

login/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <div class="form-inline">
        <div class="form-group mb-2">
          <form action="{% url 'basic_app:login' %}" method="post">
            {% csrf_token %}
            <input class="form-control" type="text" name="username" required="true" placeholder="Enter your username">
            <input class="form-control" type="password" name="password" required="true" placeholder="Enter your password">
            <input class="btn btn-primary" id="inputpassword2" type="submit" value="Login">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

login/templates/basic_app/registration.html
{% extends 'basic_app/base.html'%}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Successfully registered!</h1>
      {% else %}
      <h1>Register your account!</h1>
      <form enctype="multipart/form-data" method="post">
        <table>
          {{ user_form.as_table }}
          {{ profile_form.as_table }}
        </table>
        <input class="btn btn-primary" type="submit" name="" value="Register">
        {% csrf_token %}
      </form>
      {% endif %}
    </div>
  </div>
{% endblock %}